const express = require("express");
const OpenAI = require("openai").default;
const puppeteer = require("puppeteer");

const app = express();
app.use(express.json());

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

/* -----------------------------
   BASIC TEST ROUTES
------------------------------ */

app.get("/", (req, res) => {
  res.send("FairVia server running");
});

app.get("/health", (req, res) => {
  res.json({ status: "ok" });
});

/* -----------------------------
   AI REPORT GENERATION
------------------------------ */

app.post("/generate-report", async (req, res) => {
  try {

    const data = req.body;

    const prompt = `
You are a biodegradable materials consultant.

Generate a short professional screening report.

Application: ${data.application}
Current Material: ${data.material}
Bio Material: ${data.bio_material}
Equipment: ${data.equipment}
Concern: ${data.concern}
Stage: ${data.stage}
Notes: ${data.notes}

Return a structured technical evaluation with:

Compatibility Level
Technical Observations
Potential Risks
Suggested Next Step
`;

    const completion = await openai.chat.completions.create({
      model: "gpt-4.1-mini",
      messages: [
        {
          role: "system",
          content: "You are a polymer processing expert."
        },
        {
          role: "user",
          content: prompt
        }
      ]
    });

    const report = completion.choices[0].message.content;

    /* -----------------------------
       HTML TEMPLATE
    ------------------------------ */

    const html = `
<html>
<head>
<meta charset="UTF-8">
<style>

body{
font-family:Arial, Helvetica, sans-serif;
padding:40px;
line-height:1.6;
}

h1{
color:#17263c;
font-size:28px;
}

h2{
color:#17263c;
margin-top:30px;
}

.header{
border-bottom:3px solid #b4965a;
margin-bottom:30px;
padding-bottom:10px;
}

.footer{
margin-top:40px;
font-size:12px;
color:#777;
}

</style>
</head>

<body>

<div class="header">
<h1>FairVia™ Material Compatibility Screening</h1>
</div>

<div>
${report.replace(/\n/g,"<br>")}
</div>

<div class="footer">
Generated by FairVia AI Screening Engine
</div>

</body>
</html>
`;

    /* -----------------------------
       PDF GENERATION
    ------------------------------ */

    const browser = await puppeteer.launch({
      args: ["--no-sandbox"]
    });

    const page = await browser.newPage();

    await page.setContent(html);

    const pdf = await page.pdf({
      format: "A4",
      printBackground: true
    });

    await browser.close();

    /* -----------------------------
       RETURN PDF
    ------------------------------ */

    res.set({
      "Content-Type": "application/pdf",
      "Content-Disposition": "attachment; filename=fairvia_report.pdf"
    });

    res.send(pdf);

  } catch (error) {

    console.error("ERROR:", error);

    res.status(500).json({
      error: "Report generation failed",
      message: error.message
    });

  }
});

/* -----------------------------
   SERVER START
------------------------------ */

const PORT = process.env.PORT || 8080;

app.listen(PORT, "0.0.0.0", () => {
  console.log("FairVia server running on port " + PORT);
});
